name: PublishAddon

on:
  push:
    branches:
      - master
      - main

jobs:
  oublish-addon:
    uses:  Pepperi-Addons/training-saar.g/.github/workflows/publish.yml@main
    secrets:
      PEPPERI_ADDON_PUBLISH_KEY: ${{ secrets.PEPPERI_ADDON_PUBLISH_KEY }}
